/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/cases': typeof CasesRoute
  '/reports': typeof ReportsRoute
  '/screening': typeof ScreeningRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/cases': typeof CasesRoute
  '/reports': typeof ReportsRoute
  '/screening': typeof ScreeningRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/cases': typeof CasesRoute
  '/reports': typeof ReportsRoute
  '/screening': typeof ScreeningRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/batch'
    | '/cases'
    | '/reports'
    | '/screening'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/batch'
    | '/cases'
    | '/reports'
    | '/screening'
    | '/watchlists'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/batch'
    | '/cases'
    | '/reports'
    | '/screening'
    | '/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  BatchRoute: typeof BatchRoute
  CasesRoute: typeof CasesRoute
  ReportsRoute: typeof ReportsRoute
  ScreeningRoute: typeof ScreeningRoute
  WatchlistsRoute: typeof WatchlistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  BatchRoute: BatchRoute,
  CasesRoute: CasesRoute,
  ReportsRoute: ReportsRoute,
  ScreeningRoute: ScreeningRoute,
  WatchlistsRoute: WatchlistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
